id: e97754eb8f9a4523b58b4581b119ee89
title: Toh_544-Siddhaikavira-v1
type: translation
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-04-10T04:55:38.201Z'
  creationid: celso
  eft-text-id: UT22084-089-001
  eft-text-version: 1.17.2 2019
  xmlns-eft: http://read.84000.co/ns/1.0
